# # Use Node.js image
# FROM node:16
# WORKDIR /app

# # Install dependencies
# COPY package.json package-lock.json ./
# RUN npm install

# # Copy application files
# COPY . .

# # Expose the port
# EXPOSE 3000

# # Start the application
# CMD ["node", "app.js"]


# Stage 1

FROM node:16-alpine AS build

WORKDIR /app
COPY package*.json .
RUN npm install
COPY . .

# Stage @
FROM node:16-alpine 
WORKDIR /app
COPY --from=build /app /app/
EXPOSE 3000
CMD ["node", "app.js"]